const key="hat_tasks";
let tasks=JSON.parse(localStorage.getItem(key)||"null")||[
{id:1,title:"Computing Assignment",subject:"Computing",description:"Complete prototype documentation",date:"2026-08-17",time:"23:59",priority:"Medium",reminder:"1 day before",completed:true},
{id:2,title:"Food Studies Practical Plan",subject:"Food Studies",description:"Finish practical plan",date:"2026-08-18",time:"13:00",priority:"Medium",reminder:"1 day before",completed:false},
{id:3,title:"Maths Homework",subject:"Mathematics",description:"Complete worksheet",date:"2026-08-19",time:"16:00",priority:"High",reminder:"1 day before",completed:false},
{id:4,title:"English Essay",subject:"English",description:"Finish essay",date:"2026-08-20",time:"09:00",priority:"Medium",reminder:"2 days before",completed:false},
{id:5,title:"Geography Fieldwork Report",subject:"Geography",description:"Complete fieldwork report",date:"2026-08-22",time:"15:00",priority:"Low",reminder:"1 week before",completed:false},
{id:6,title:"Biology SAC",subject:"Biology",description:"Revise Unit 2 content",date:"2026-08-25",time:"11:30",priority:"High",reminder:"1 week before",completed:false},
{id:7,title:"Maths Practice Test",subject:"Mathematics",description:"Complete practice test",date:"2026-08-27",time:"16:00",priority:"Low",reminder:"2 days before",completed:true}
];
let settings=JSON.parse(localStorage.getItem("hat_settings")||"null")||{dark:false,reminders:true,defaultReminder:"1 day before"};
let cal=new Date(2026,7,1),selected="2026-08-19";

function save(){localStorage.setItem(key,JSON.stringify(tasks))}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function fmt(d){return new Date(d+"T12:00:00").toLocaleDateString("en-AU",{day:"2-digit",month:"short",year:"numeric"})}
function today(){return new Date().toISOString().slice(0,10)}
function overdue(t){return !t.completed && new Date(t.date+"T"+t.time)<new Date()}
function show(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.target===id));render()}
function openAddTask(){document.getElementById("modal").classList.remove("hidden");document.getElementById("date").value=today()}
function closeModal(){document.getElementById("modal").classList.add("hidden");document.getElementById("taskForm").reset()}
document.getElementById("taskForm").addEventListener("submit",e=>{e.preventDefault();const t={id:Date.now(),title:title.value.trim(),subject:newSubject.value,description:description.value.trim(),date:date.value,time:time.value,priority:newPriority.value,reminder:newReminder.value,completed:false};if(!t.title||!t.subject||!t.date)return;tasks.push(t);save();closeModal();show("tasks")});
function render(){renderHome();renderTasks();renderProgress();renderReminders();renderCalendar();applySettings()}
function renderHome(){const p=tasks.filter(t=>!t.completed).length,c=tasks.filter(t=>t.completed).length,o=tasks.filter(overdue).length,td=tasks.filter(t=>t.date===today()).length;pendingCount.textContent=p;completedCount.textContent=c;overdueCount.textContent=o;todayCount.textContent=td;summary.textContent=`You have ${p} tasks still to do${o?`, including ${o} overdue.`:"."}`;const pct=tasks.length?Math.round(c/tasks.length*100):0;progressPct.textContent=pct+"%";progressText.textContent=`${c} of ${tasks.length} tasks completed`;document.querySelector(".progress-circle").style.setProperty("--progress",pct*3.6+"deg");upcoming.innerHTML=tasks.filter(t=>!t.completed).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5).map(card).join("")||"<p>No upcoming tasks.</p>";const r=settings.reminders?tasks.filter(t=>!t.completed).length:0;reminderSummary.textContent=settings.reminders?`${r} active reminder${r===1?"":"s"}.`:"Reminders are turned off."}
function card(t){return `<div class="task-card"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.subject)} · ${fmt(t.date)} · ${t.time}</div><div class="badges"><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span><span class="badge">${t.completed?"Completed":"Pending"}</span>${overdue(t)?'<span class="badge high">Overdue</span>':""}</div><div class="task-actions"><button class="small" onclick="toggleTask(${t.id})">${t.completed?"Mark pending":"Mark completed"}</button><button class="small" onclick="delTask(${t.id})">Delete</button></div></div>`}
function renderTasks(){const q=(document.getElementById("search")?.value||"").toLowerCase(),s=document.getElementById("subject")?.value||"",st=document.getElementById("status")?.value||"",p=document.getElementById("priority")?.value||"";const arr=tasks.filter(t=>(!q||(`${t.title} ${t.subject} ${t.description}`).toLowerCase().includes(q))&&(!s||t.subject===s)&&(!st||(st==="completed"?t.completed:!t.completed))&&(!p||t.priority===p)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));taskList.innerHTML=arr.map(card).join("")||'<div class="panel"><p>No tasks match your filters.</p></div>'}
function toggleTask(id){const t=tasks.find(x=>x.id===id);if(t){t.completed=!t.completed;save();render()}}
function delTask(id){if(confirm("Delete this task?")){tasks=tasks.filter(t=>t.id!==id);save();render()}}
function renderProgress(){const total=tasks.length,c=tasks.filter(t=>t.completed).length,o=tasks.filter(overdue).length,p=total-c,pct=total?Math.round(c/total*100):0;document.getElementById("total").textContent=total;document.getElementById("pCompleted").textContent=c;document.getElementById("pPending").textContent=p;document.getElementById("pOverdue").textContent=o;bigBar.style.width=pct+"%";bigLabel.textContent=pct+"%";const subs=["English","Mathematics","Biology","Computing","Geography","Food Studies"];subjectProgress.innerHTML=subs.map(s=>{const a=tasks.filter(t=>t.subject===s),c2=a.filter(t=>t.completed).length,p2=a.length?Math.round(c2/a.length*100):0;return `<div class="subject-row"><div class="row"><b>${s}</b><span>${p2}%</span></div><div class="subject-bar"><i style="width:${p2}%"></i></div><small>${c2} of ${a.length} completed</small></div>`}).join("")}
function renderReminders(){remindersOn.checked=settings.reminders;defaultReminder.value=settings.defaultReminder;reminderList.innerHTML=tasks.filter(t=>!t.completed).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(t=>`<div class="task-card"><div class="task-title">🔔 ${esc(t.title)}</div><div class="task-meta">${esc(t.subject)} · ${fmt(t.date)} · ${t.reminder}</div><div class="badges"><span class="badge">${overdue(t)?"Overdue":t.date===today()?"Due today":"Upcoming"}</span></div></div>`).join("")||'<div class="panel"><p>No active reminders.</p></div>'}
function saveSettings(){settings.reminders=remindersOn.checked;settings.defaultReminder=defaultReminder.value;localStorage.setItem("hat_settings",JSON.stringify(settings));render()}
function applySettings(){document.documentElement.classList.toggle("dark",settings.dark);profileDark.checked=settings.dark;themeBtn.textContent=settings.dark?"☀":"☾"}
function toggleTheme(){settings.dark=!settings.dark;localStorage.setItem("hat_settings",JSON.stringify(settings));render()}
function toggleThemeProfile(){settings.dark=profileDark.checked;localStorage.setItem("hat_settings",JSON.stringify(settings));render()}
themeBtn.onclick=toggleTheme;reminderBtn.onclick=()=>show("reminders");
function moveMonth(n){cal.setMonth(cal.getMonth()+n);renderCalendar()}
function renderCalendar(){const y=cal.getFullYear(),m=cal.getMonth();monthTitle.textContent=cal.toLocaleString("en-AU",{month:"long",year:"numeric"});const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7;let h="";for(let i=0;i<start;i++)h+="<div></div>";for(let d=1;d<=days;d++){const dt=new Date(y,m,d),k=dt.toISOString().slice(0,10),arr=tasks.filter(t=>t.date===k);h+=`<button class="${k===today()?"today":""}" onclick="pickDate('${k}')"><div class="cal-date">${d}</div>${arr.slice(0,2).map(t=>`<div class="cal-task">${esc(t.title)}</div>`).join("")}</button>`}calendarGrid.innerHTML=h;renderSelected()}
function pickDate(k){selected=k;renderSelected()}
function renderSelected(){selectedTitle.textContent="Tasks on "+fmt(selected);const arr=tasks.filter(t=>t.date===selected);selectedTasks.innerHTML=arr.map(t=>`<div class="task-card"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.subject)} · ${t.time}</div><div class="badges"><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span><span class="badge">${t.completed?"Completed":"Pending"}</span></div></div>`).join("")||"<p>No tasks for this date.</p>"}
render();
